# Generated by Django 5.1.4 on 2024-12-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('na', models.CharField(max_length=25)),
                ('tna', models.CharField(max_length=25)),
            ],
        ),
    ]
